name: cicd

on:
  push:
    branches: [main]

jobs:
  push:
    runs:
      using: "node18"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sergeysova/jq-action@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: install
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: push to s3
        run: aws s3 sync dist/ s3://rosscalimlim.me/

      - name: invalidate cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
