name: build_check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sergeysova/jq-action@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: build site
        run: yarn buildSite

      - name: gen resume data
        run: yarn genResumeJson

      - name: build resume
        uses: addnab/docker-run-action@v3
        with:
          image: rosscalimlim/docker-latexmk
          shell: bash
          options: -v ${{ github.workspace }}:/data
          run: |
            ls -al /root
            bash /root/entry.sh -lualatex -cd -output-directory=../../../dist/files  src/cv/tex/plush-cv/ross-calimlim-resume
